### ISSUE TITLE
Error running with express and nextjs - TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be of type string or an instance of Buffer. Received an instance of Promise

### ISSUE THREAD

**Issue by dominathan** [Zooz/prometheus-api-metrics#61]
I'm using express with nextjs, but pulled the express app out.  Code look llike so

```js
// server.js 
const next = require('next');
const { initializeExpressWithNext } = require('./src/server/app');
const dev = process.env.NODE_ENV !== 'production';
const nextApplication = next({ dev });
const handle = nextApplication.getRequestHandler();

nextApplication.prepare().then(() => {
  const app = initializeExpressWithNext(handle);

  app.listen(3000, (err) => {
    if (err) throw err;
    console.log('Ready on http://localhost:3000');
  });
});


//app.js
const express = require('express');
const cors = require('cors');
const apiMetrics = require('prometheus-api-metrics');

const questionnaireRoutes = require('./routes/questionnaire');
const recaptchaRoutes = require('./routes/recaptcha');

/**
 * @function initializeExpressWithNext
 * @description to run this with nextjs, we need to pass in a callbackhandler
 * for all routes that are not defined by express, we do this by wrapping express
 * in a function to initialize the callback and runtime
 * @param {function} callbackHandler - nextjs server callbackhandler
 * @return {*} express application
 */
function initializeExpressWithNext(callbackHandler) {
  const app = express();
  app.use(apiMetrics());

  app.get('/healthcheck', cors(), (_, res) => {
    res.status(200).send();
  });

  app.use('/', questionnaireRoutes);
  app.use('/', recaptchaRoutes);

  app.get('*', (req, res) => {
    return callbackHandler(req, res);
  });

  return app;
}

module.exports = { initializeExpressWithNext };
```

The app starts fine, but when i navigate to /metrics or metrics.json, I get the following error

```
TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be of type string or an instance of Buffer. Received an instance of Promise
    at ServerResponse.end (_http_outgoing.js:784:13)
    at ExpressMiddleware.middleware (/Users/nathanhall/bwell/medstar-squeeze-page/node_modules/prometheus-api-metrics/src/express-middleware.js:99:24)
    at Layer.handle [as handle_request] (/Users/nathanhall/bwell/medstar-squeeze-page/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/nathanhall/bwell/medstar-squeeze-page/node_modules/express/lib/router/index.js:317:13)
    at /Users/nathanhall/bwell/medstar-squeeze-page/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/nathanhall/bwell/medstar-squeeze-page/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/nathanhall/bwell/medstar-squeeze-page/node_modules/express/lib/router/index.js:275:10)
    at expressInit (/Users/nathanhall/bwell/medstar-squeeze-page/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/Users/nathanhall/bwell/medstar-squeeze-page/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/nathanhall/bwell/medstar-squeeze-page/node_modules/express/lib/router/index.js:317:13)
    at /Users/nathanhall/bwell/medstar-squeeze-page/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/nathanhall/bwell/medstar-squeeze-page/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/nathanhall/bwell/medstar-squeeze-page/node_modules/express/lib/router/index.js:275:10)
    at query (/Users/nathanhall/bwell/medstar-squeeze-page/node_modules/express/lib/middleware/query.js:45:5)
    at Layer.handle [as handle_request] (/Users/nathanhall/bwell/medstar-squeeze-page/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/nathanhall/bwell/medstar-squeeze-page/node_modules/express/lib/router/index.js:317:13)
    ```
    
    I'll try to see if I can figure it out and make. PR but I'm on a tight timeline

**Comment by nautilor** [comment]
same problem here using express only, also calling `/metrics.json` returns always an empty json

**Comment by idanto** [comment]
This is related to a change in [prom-client 13.x](https://github.com/siimon/prom-client/blob/master/CHANGELOG.md#1300---2020-12-16)

@dominathan please fix the failed tests so we can approve the MR and release a major version

**Comment by nautilor** [comment]
Yeah I noticed that by using prom client only and await it it works fine

**Comment by dominathan** [comment]
Not super familiar with sinon and async await.  When I have more time I'll try to get the test to pass but if you have better ideas feel to fix it.

**Comment by kobik** [comment]
@dominathan , please let me know if you need any help with that

**Comment by dominathan** [comment]
I would please,  I don't have any quick solution to fix the tests for different node versions.  Currently just using prom-client directly.

**Comment by kamanwu-sh** [comment]
I have this issue as well.  I am using:   "prom-client": "^14.0.1",
